// UTIs from https://developer.apple.com/library/archive/documentation/Miscellaneous/Reference/UTIRef/Articles/System-DeclaredUniformTypeIdentifiers.html

let allowedPublicUTIs: Set = [
    "public.text",
    "public.plain-text",
    "public.rtf",
    "public.html",
    "public.xml",
    "public.source-code",
    "public.c-source",
    "public.objective-c-source",
    "public.c-plus-plus-source",
    "public.objective-c-plus-plus-source",
    "public.c-header",
    "public.c-plus-plus-header",
    "com.sun.java-source",
    "public.script",
    "public.assembly-source",
    "com.apple.rez-source",
    "public.mig-source",
    "com.apple.symbol-export",
    "com.netscape.javascript-source",
    "public.shell-script",
    "public.csh-script",
    "public.perl-script",
    "public.python-script",
    "public.ruby-script",
    "public.php-script",
    "com.sun.java-web-start",
    "com.apple.applescript.text",
    "com.apple.applescript.script",
    "public.object-code",
    "com.apple.mach-o-binary",
    "com.apple.pef-binary",
    "com.microsoft.windows-executable",
    "com.microsoft.windows-dynamic-link-library",
    "com.sun.java-class",
    "com.sun.java-archive",

    "com.apple.quartz-composer-composition",

    "org.gnu.gnu-tar-archive",
    "public.tar-archive",
    "org.gnu.gnu-zip-archive",
    "org.gnu.gnu-zip-tar-archive",
    "com.apple.binhex-archive",
    "com.apple.macbinary-archive",

    "public.url",

    "public.vcard",

    "public.image",
    "public.fax",
    "public.jpeg",
    "public.jpeg-2000",
    "public.tiff",
    "public.camera-raw-image",
    "com.apple.pict",
    "com.apple.macpaint-image",
    "public.png",
    "public.xbitmap-image",
    "com.apple.quicktime-image",
    "com.apple.icns",

    "public.audiovisual-content",
    "public.movie",
    "public.video",
    "com.apple.quicktime-movie",
    "public.avi",
    "public.mpeg",
    "public.mpeg-4",
    "public.3gpp",
    "public.3gpp2",

    "public.audio",
    "public.mp3",
    "public.mpeg-4-audio",
    "com.apple.protected-mpeg-4-audio",
    "public.ulaw-audio",
    "public.aifc-audio",
    "public.aiff-audio",
    "com.apple.coreaudio-format",

    "public.directory",
    "public.folder",
    "public.volume",
    "com.apple.package",
    "com.apple.bundle",
    "public.executable",
    "com.apple.application",
    "com.apple.application-bundle",
    "com.apple.application-file",

    "public.cpio-archive",
    "com.pkware.zip-archive",
    "com.apple.rtfd",
    "public.font",

    "com.adobe.pdf",
    "com.adobe.postscript",
    "com.adobe.photoshop-image",
    "com.adobe.illustrator.ai-image",

    "com.compuserve.gif",
    "com.microsoft.bmp",
    "com.microsoft.ico",

    "com.microsoft.word.doc",
    "com.microsoft.excel.xls",
    "com.microsoft.powerpoint.ppt",
    "com.microsoft.waveform-audio",
    "com.microsoft.advanced-system-format",
    "com.microsoft.windows-media-wm",
    "com.microsoft.windows-media-wmv",
    "com.microsoft.windows-media-wmp",
    "com.microsoft.windows-media-wma",
    "com.microsoft.advanced-stream-redirector",
    "com.microsoft.windows-media-wmx",
    "com.microsoft.windows-media-wvx",
    "com.microsoft.windows-media-wax",

    "com.apple.keynote.key",
    "com.apple.keynote.kth",
    "com.truevision.tga-image",
    "com.sgi.sgi-image",
    "com.ilm.openexr-image",
    "com.kodak.flashpix.image",

    "com.real.realmedia",
    "com.real.realaudio",
    "com.real.smil",
    "com.allume.stuffit-archive",
]

/*
let allowedPublicUTIsDict: Dictionary<AnyHashable, Any> = [
    "public": [
        "text",
        "plain-text",
        "rtf",
        "html",
        "xml",
        "source-code",
        "c-source",
        "objective-c-source",
        "c-plus-plus-source",
        "objective-c-plus-plus-source",
        "c-header",
        "c-plus-plus-header",
        "script",
        "assembly-source",
        "mig-source",
        "shell-script",
        "csh-script",
        "perl-script",
        "python-script",
        "ruby-script",
        "php-script",
        "object-code",
    ],
    "com": [
        "apple": [
            "rez-source",
            "symbol-export",
            "mach-o-binary",
            "pef-binary",
            "applescript": [
                "text",
                "script",
            ],
        ],
        "microsoft": [
            "windows-executable",
            "windows-dynamic-link-library",
        ],
        "sun": [
            "java-source",
            "java-web-start",
        ],
        "netscape": [
            "javascript-source"
        ],
    ]
]
*/
